name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.7.0'  # Specify the latest LTS version explicitly

    - name: Run setup script
      run: |
        chmod +x generate_electron_project.sh
        ./setup_node_gyp.sh

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Package app
      run: pnpm run package

    - name: Build RPM
      run: pnpm run rpm

    - name: Upload RPM artifact
      uses: actions/upload-artifact@v2
      with:
        name: rpm-package
        path: dist/installers/*.rpm
